# Generated by Django 3.1.4 on 2022-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
